import {useState,useEffect} from 'react';
import {defaults} from './lib/config';
import {apiFetch,asset,home} from './lib/platform';
export default function Home(){const [services,setServices]=useState(defaults.services);useEffect(()=>{apiFetch('/api/availability').then(r=>r.json()).then(d=>{if(d.config)setServices(d.config.services)}).catch(()=>{});},[]);return <main className="landing">
<header className="site-header"><a className="brand" href={home}>Luíza Araújo<span>MAKEUP ARTIST</span></a><nav><a href="#assinatura">A experiência</a><a href="#portfolio">Portfólio</a><a className="outline-link" href="#/agendar">Reservar horário</a></nav></header>
<section className="hero"><div className="hero-copy"><p className="eyebrow">BELEZA COM IDENTIDADE</p><h1>Não é sobre<br/>ser outra.<br/><em>É sobre você.</em></h1><p className="hero-intro">Sua essência, realçada com intenção.<br/>Uma maquiagem à altura do seu momento.</p><a className="gold-button" href="#/agendar">Quero reservar meu horário</a><p className="cta-caption">Escolha sua data. Viva a sua melhor versão.</p></div><div className="hero-visual"><div className="photo-line"/><img src={asset('images/luiza.webp')} alt="Luíza Araújo, maquiadora, segurando um pincel" width="1080" height="1080" fetchPriority="high"/><div className="portrait-label"><span>O olhar por trás da beleza</span><strong>Luíza Araújo</strong></div><span className="vertical-note">MAQUIAGEM AUTORAL · CUIDADO EM CADA DETALHE</span></div><div className="hero-bottom"><span>Social · Noivas · Ensaios</span><a href="#portfolio">Descubra meu trabalho</a><span>BELEZA QUE PERMANECE NA MEMÓRIA</span></div></section>
<section id="assinatura" className="signature"><p className="eyebrow">A EXPERIÊNCIA LUÍZA ARAÚJO</p><div><h2>O detalhe muda tudo.<br/><em>O cuidado também.</em></h2><div className="signature-text"><p>Antes do primeiro pincel, vem a escuta. Seu estilo, sua pele e o que você quer sentir quando se olhar no espelho.</p><p>Da preparação ao acabamento, cada escolha tem um propósito: valorizar o que já é seu, com uma beleza que faz sentido para você.</p><a href="#/agendar" className="text-link">Escolha seu momento</a></div></div><div className="detail-strip"><span>01 / Escuta e personalização</span><span>02 / Preparação cuidadosa da pele</span><span>03 / Acabamento com intenção</span></div></section>
<section id="portfolio" className="portfolio"><div className="section-heading"><div><p className="eyebrow">BELEZA NA VIDA REAL</p><h2>Cada rosto,<br/><em>uma assinatura.</em></h2></div><p>Do delicado ao marcante.<br/>Sempre com você no centro.</p></div><div className="photo-grid"><figure><img src={asset('images/noiva.webp')} alt="Maquiagem delicada em uma noiva com vestido branco" width="1080" height="1500" loading="lazy"/><figcaption>01 <span>Delicadeza que celebra</span></figcaption></figure><figure><img src={asset('images/dourado.webp')} alt="Maquiagem com sombra dourada e pele luminosa" width="1080" height="1080" loading="lazy"/><figcaption>02 <span>Luz em cada detalhe</span></figcaption></figure><figure><img src={asset('images/glam.webp')} alt="Maquiagem marcante com olhos esfumados" width="1080" height="1080" loading="lazy"/><figcaption>03 <span>Presença sem esforço</span></figcaption></figure><figure><img src={asset('images/smokey.webp')} alt="Detalhe de maquiagem esfumada e delineado" width="1080" height="1080" loading="lazy"/><figcaption>04 <span>Um olhar inesquecível</span></figcaption></figure></div></section>
<section className="services" id="servicos"><div><p className="eyebrow">PARA O SEU MOMENTO</p><h2>A ocasião é sua.<br/><em>A beleza também.</em></h2><p>Escolha a experiência que combina com o que você vai viver.</p></div><div className="service-list">{services.map((s,i)=><a key={s.id} href={'#/agendar?servico='+s.id}><span className="service-number">0{i+1}</span><div><h3>{s.name}</h3><p>{s.description}</p><span>{s.duration} minutos · Valor sob consulta</span></div><span className="service-action">Reservar</span></a>)}</div></section>
<section className="final-cta"><p className="eyebrow">SEU MOMENTO COMEÇA AQUI</p><h2>Se reconheça.<br/><em>Se surpreenda.</em></h2><a href="#/agendar" className="gold-button">Garanta seu horário</a><p>Uma escolha simples para um momento especial.</p></section><footer><a className="brand" href={home}>Luíza Araújo<span>MAKEUP ARTIST</span></a><span>Beleza com identidade. Cuidado com você.</span><a href="#/admin">Área da profissional</a><small>© {new Date().getFullYear()} Luíza Araújo</small></footer></main>}
